### PR TITLE
Fix some compile errors on openSUSE Leap 15.0

### PR DESCRIPTION
**Pull request by linxiaohui**
When compile on openSUSE Leap 15.0(which have the following version of gcc & wxWidgets)
- `g++ -v` returns `gcc version 7.3.1 `
- `wx-config --version` returns `3.1.1`

There would be some errors,such as

- `src/dialog/wxmedit_about_dialog.cpp:75:103: error: ‘wxTE_AUTO_SCROLL’ was not declared in this scope`

- `src/dialog/wxmedit_options_dialog.cpp:826:77: error: cannot convert ‘const wxString’ to ‘const wxChar* {aka const wchar_t*}’ for argument ‘1’ to ‘wxString FilterChar(const wxChar*)’`

- `src/wxm/utils.cpp:208:23: error: ‘wxCharStringHash’ is not a member of ‘wxStringHash’`

- ...

This pull request fixes these errors, and please consider whether it is good to merge it. 

Thank you

### CODE REVIEW

**Comment by hltj** [comment]
Thanks.
多谢。

File: src/dialog/wxmedit_about_dialog.h [hunk 1]
```diff
@@ -8,6 +8,10 @@
 #ifndef WXMEDIT_ABOUT_DIALOG_H
 #define WXMEDIT_ABOUT_DIALOG_H
 
+#ifndef wxTE_AUTO_SCROLL
+#define wxTE_AUTO_SCROLL 0
+#endif
+
 #ifdef _MSC_VER
```
Comment (hltj) [inline src/dialog/wxmedit_about_dialog.h]: this should move to bellow all included files

**Comment by hltj** [comment]
wxTranslation().wc_str() is also 2.8 incompatible, should fix them...
