### ISSUE TITLE
Where is the MacOSX download ?

### ISSUE THREAD

**Issue by deesea** [wxMEdit/wxMEdit#57]
Pardon my ignorance, but where / what distribution is for MacOSX ?  It's not listed in the Operating System list.
- deesea

**Comment by jjtx** [comment]
I just want to thank you for the instructions, and confirm I got it working on OS X 10.10, and the program is just what I needed (a hex editor that displays Chinese).  I followed the instructions exactly, but received the "Error: Unable to initialize gtk, is DISPLAY set properly?" also.  Then I did "ports install xorg-server", but still got the same error (maybe because I didn't know how to logout and log back in, and I didn't try to reboot yet).  Then I installed XQuartz.  After I rebooted, I was able to run the program by typing "wxmedit" in the install directory in terminal.

**Comment by hltj** [comment]
OK. Updated.

**Comment by lordscales91** [comment]
I tried to follow this procedure with latest version (3.1) and I got this errors:

```c++
src/dialog/wxm_conv_enc_dialog.h:47:3: error: use of undeclared identifier 'std'
                std::wstring GetEncoding() const;
                ^
src/dialog/wxm_conv_enc_dialog.cpp:94:23: error: no matching member function for
      call to 'Append'
                WxComboBoxEncoding->Append(xm::EncodingManager::Instance...
                ~~~~~~~~~~~~~~~~~~~~^~~~~~
src/dialog/wxm_conv_enc_dialog.cpp:101:11: error: no viable conversion from
      'std::wstring' (aka 'basic_string<wchar_t, char_traits<wchar_t>,
      allocator<wchar_t> >') to 'wxString'
        wxString convenc = encmgr.GetEncodingName(0);
                 ^         ~~~~~~~~~~~~~~~~~~~~~~~~~
```

The first one is caused because there is a missing header reference to [src/dialog/wxm_conv_enc_dialog.h](https://github.com/hltj/wxMEdit/blob/61a2aa07c2305b050720812c57a562e6d234a6b8/src/dialog/wxm_conv_enc_dialog.h)

I added `#include <string>` in that file and the error dissappeared. The other 2 are produced because `std::wstring` can't be converted to `wxString` directly. Starting from wxWidgets 3.0 there is a constructor to make de conversion, but I don't know how to do it on 2.8

**Comment by hltj** [comment]
@lordscales91 fixed.
Awfully sorry for so late.

**Comment by shipd** [comment]
Getting the following error: 

[wxMEdit-2.9.9.2]: make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in syntax
make[2]: Nothing to be done for `all'.
Making all in po
make[2]: Nothing to be done for `all'.
make[2]: MKDIR_P@: No such file or directory
make[2]: *** [src/wxm/encoding/.dirstamp] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by hltj** [comment]
@shipd do you follow the steps [above](#issuecomment-31417588) ?

**Comment by RaimonTr** [comment]
Working on OS X 10.15.
Thank you

**Comment by unnamed7** [comment]
Got this error on OSX12.6

echo './'`src/xm/encoding/multibyte.cpp
src/xm/encoding/multibyte.cpp:36:27: error: use of undeclared identifier 'FALSE'
        ucnv_setFallback(m_ucnv, FALSE);

**Comment by hltj** [comment]
> Got this error on OSX12.6
> 
> echo './'`src/xm/encoding/multibyte.cpp src/xm/encoding/multibyte.cpp:36:27: error: use of undeclared identifier 'FALSE' ucnv_setFallback(m_ucnv, FALSE);

The latest code 3.2RC (3.1.0.90) fixed it.
https://wxmedit.github.io/zh_CN/downloads.html#prerelease
http://downloads.sourceforge.net/project/wxmedit/prerelease/3.1.0.90/wxMEdit-3.1.0.90.tar.gz

This release is actually stable enough. While waiting for localization and packaging for each system, the formal 3.2 is expected to be released in two weeks.
